### ISSUE TITLE
Task hangs or randomly reboot

### ISSUE THREAD

**Issue by 01matrix01** [ju6ge/rf433mhz#1]
Hi @Felix5721,
I'm testing this repo, I simply add this code:

uint16_t counter = 0;

void counter_task(void *pvParameters) {
	while(1) {
		vTaskDelay(100);
		counter++;
		printf("Counter = %d\r\n",counter);
	}
}

And on user_init:

	//start tasks
	//xTaskCreate(rf433mhz_transmit, "transmitter_rf", 256, NULL, 1, NULL);
	xTaskCreate(rf433mhz_recieve, "reciever_rf", 256, NULL, 1, NULL);
	xTaskCreate(counter_task, "counter_task", 256, NULL, 1, NULL);

So, no transmit Task is enabled, only receive + simple counter task.

 Errors:
************************************************
Error 1:

Counter = 110
Counter = 111
Counter = 112

ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x40100000, len 1828, room 16

0x40100000: _stext at ??:?

tail 4
chksum 0xcf
load 0x3ffe8000, len 216, room 4
tail 4
chksum 0xce
csum 0xce
Counter = 1
Counter = 2
Counter = 3
************************************************
Error 2:

Counter = 259
Counter = 260
Counter = 261
Recieved message with data: 15207911
Recieved message with data: 15207911
Recieved message with data: 15207911
Recieved message with data: 15207911
Recieved message with data: 15207911
ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 1828, room 16

0x40100000: _stext at ??:?

tail 4
chksum 0xcf
load 0x3ffe8000, len 216, room 4
tail 4
chksum 0xce
csum 0xce
Counter = 1
Counter = 2
************************************************

**Comment by ju6ge** [comment]
I have been experiencing this from time to time as well, and I have spent a lot of time trying to figure out why this happens. But unfortunately I was not able to find any conclusive answer to why this happens or that even that it is related to the code i wrote.

My best guess is that it is related to the hardware watchdog since it will reset the esp if a task keeps control of the CPU for to long.

I am currently busy working on other projects and don't have the time to look into this, but any Ideas or other insights on how to resolve the issue are greatly appreciated!

**Comment by oremic** [comment]
> Hi @Felix5721,
> I'm testing this repo, I simply add this code:
> 
> uint16_t counter = 0;
> 
> void counter_task(void *pvParameters) {
> while(1) {
> vTaskDelay(100);


found some solution?

**Comment by ju6ge** [comment]
After a lot of debugging, the main problem is that, if your program code takes a significant amount of time to execute, the software watchdog will reset the chip. To find out more about this here is the link to the espressif FAQ (https://www.espressif.com/en/products/hardware/esp8266ex/resources).

Since the code uses interrupts it is not clear how often the watchdog is feed even if your tasks do not run permanently. So a solution could be to manually feed the watchdog from time to time. But it highly depends on what the rest of your code does and if you use the RTOS sdk correctly! So this is not a issue with the code in this repo, more of a issue of how to integrate it correctly with the rest of the system. So I am closing this issue now.

Note: I have been using this code to trigger the rf sockets in my room via mqtt and it works for me.
